"""add new column

Revision ID: 5d2975802f9d
Revises: eb9ab08a377a
Create Date: 2018-02-08 10:38:07.070554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2975802f9d'
down_revision = 'eb9ab08a377a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'message')
    # ### end Alembic commands ###
